services:
  - type: web
    name: unitalk-backend
    runtime: python
    rootDir: unitalk_backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn unitalk_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false   # set to your-service.onrender.com,localhost
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
